# Generated by Django 5.1.1 on 2024-12-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_alter_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Message',
        ),
    ]
