# Generated by Django 5.1.1 on 2024-12-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_contact_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Contact',
        ),
    ]
