# Generated by Django 5.1.1 on 2024-12-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_message_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
